version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cobrasnake
      MYSQL_USER: cobrasnake
      MYSQL_PASSWORD: 6NA8nCRaRYRdePaB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SnakeSQL/SnakeSQL.sql:/docker-entrypoint-initdb.d/SnakeSQL.sql

  app:
    build: .
    restart: always
    ports:
      - "5020:5020"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=cobrasnake
      - DB_PASSWORD=6NA8nCRaRYRdePaB
      - DB_NAME=cobrasnake

volumes:
  db_data:
